CREATE SEQUENCE user_id_seq;

CREATE TABLE users (
    id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
file_name varchar(30) NOT NULL,
file_description text NOT NULL,
file_type varchar(15) NOT NULL,
file_uploader integer REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
file_uploaded_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
file_uploaded_to varchar(30) NOT NULL,
file_path varchar(225) NOT NULL,
file_status varchar(30) NOT NULL DEFAULT `not approved yet`,
); 

CREATE TABLE posts(
id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id integer REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
text  varchar(300),
posted_at timestamp NOT NULL,
updated_at timestamp NOT NULL
);
CREATE TABLE comments
(
    id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    writer     integer REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    comment    varchar(300) NOT NULL,
    post_id    integer REFERENCES posts(id),
    commented_at    TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
